version: "1.0"

services:
  app:
    image: patryk87/recipes-api
    container_name: api
    networks:
      - recipesnet
    ports:
      - 8080:8080
    working_dir: /app
    environment:
      SERVER_PORT: 8080

  db:
    image: patryk87/recipes-db
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      recipesnet:
        aliases:
          - recipes
    environment:
      POSTGRES_PASSWORD: 123456

networks:
  recipesnet:

volumes:
  postgres-data:
